// src/pages/Profile/styles.js
import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 16, backgroundColor: "#fff" },
  header: {},
  logo: { width: 54, height: 60 },
  welcomeText: { fontSize: 16, marginTop: 20, marginBottom: 25 },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#ddd",
    borderWidth: 1,
    paddingHorizontal: 8,
    borderRadius: 8,
    marginBottom: 25,
  },
  searchInput: { flex: 1, height: 40, marginLeft: 8 },
  navButtons: { alignItems: "center" },
  navButton: {
    width: "100%",
    backgroundColor: "#10B981",
    padding: 15,
    borderRadius: 8,
  },
  navButtonText: {
    textAlign: "center",
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
  logoutButton: { padding: 8 },
  menu: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 20,
    paddingBottom: 0,
  },
  menuButton: {
    alignItems: "center",
    position: "relative",
    width: 60,
  },
  menuButtonText: {
    fontSize: 12,
    marginTop: 6,
    textAlign: "center",
  },
  menuIconCircle: {
    width: 50,
    height: 50,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  visitantesCircle: {
    backgroundColor: "rgba(16, 185, 129, 0.12)",
  },
  historicoCircle: {
    backgroundColor: "rgba(16, 185, 129, 0.16)",
  },
  ticketsCircle: {
    backgroundColor: "rgba(16, 185, 129, 0.20)",
  },
  crachaCircle: {
    backgroundColor: "rgba(16, 185, 129, 0.24)",
  },
  menuCircle: {
    backgroundColor: "rgba(16, 185, 129, 0.28)",
  },
  notificationBadge: {
    backgroundColor: "#e02041",
    borderRadius: 12,
    paddingHorizontal: 6,
    position: "absolute",
    top: -5,
    right: 0,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  notificationText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
  },
  incidentItem: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 12,
    marginBottom: 12,
    borderRadius: 8,
  },
  incidentItemBlocked: {
    borderColor: "#e02041",
    backgroundColor: "#ffebeb",
    borderTopColor: "#e02041",
  },
  cardLeft: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  cardAvatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    marginRight: 12,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: "#eee",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cardInfo: {
    flex: 1,
    paddingRight: 10,
  },
  incidentNameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    flexWrap: "wrap",
    marginTop: 2,
  },
  incidentName: {
    fontSize: 16,
    fontWeight: "bold",
    marginRight: 8,
  },
  blockedName: { color: "#e02041" },
  blockedBadge: {
    backgroundColor: "#bd040a",
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignSelf: "flex-start",
  },
  blockedBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },
  cardDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  cardDetailColumn: {
    width: "48%",
  },
  cardDetailColumnFull: {
    width: "100%",
  },
  detailLabel: {
    fontSize: 12,
    color: "#888",
    fontWeight: "normal",
    textTransform: "uppercase",
  },
  incidentTextValue: {
    fontSize: 14,
    color: "#000",
    fontWeight: "600",
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 8,
  },
  actionButton: { padding: 8 },
  emptyContainer: {
    alignItems: "center",
    marginTop: 40,
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
  },
  logoRow: {
    marginTop: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  margin: { marginBottom: 40 },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  searchInfo: {
    backgroundColor: "#f0f0f0",
    padding: 8,
    borderRadius: 8,
    marginBottom: 0,
    marginTop: 10,
  },
  searchInfoText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
  },
  modalCloseButton: {
    padding: 5,
  },
  modalText: {
    fontSize: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  modalLabel: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
    color: "#333",
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 15,
  },
  pickerStyle: {
    height: Platform.OS === "ios" ? 150 : 50,
    width: "100%",
  },
  responsavelInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    textAlignVertical: "top",
  },
  observacaoInput: {
    minHeight: 100,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  modalButton: {
    flex: 0.48,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  modalButtonCancel: {
    backgroundColor: "#f0f0f0",
  },
  modalButtonConfirm: {
    backgroundColor: "#10B981",
  },
  modalButtonDisabled: {
    backgroundColor: "#ccc",
  },
  modalButtonCancelText: {
    color: "#333",
    fontWeight: "600",
  },
  modalButtonConfirmText: {
    color: "white",
    fontWeight: "600",
  },
  menuModalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-start",
  },
  menuModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  menuModalContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    overflow: "hidden",
  },
  menuModalHeader: {
    backgroundColor: "#f8fafc",
    paddingVertical: 20,
    paddingTop: 50,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  menuModalHeaderContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  menuModalUserInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  menuModalAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#edf2f7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  menuModalUserName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3748",
  },
  menuModalUserSetor: {
    fontSize: 14,
    color: "#718096",
    marginTop: 2,
  },
  menuModalCloseButton: {
    padding: 4,
  },
  menuModalOptions: {
    flex: 1,
    paddingVertical: 16,
  },
  menuModalOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  menuModalIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  menuModalOptionContent: {
    flex: 1,
  },
  menuModalOptionTitle: {
    fontSize: 15,
    fontWeight: "500",
    color: "#2d3748",
    marginBottom: 2,
  },
  menuModalOptionDescription: {
    fontSize: 12,
    color: "#718096",
  },
  menuModalFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    alignItems: "center",
  },
  menuModalVersion: {
    fontSize: 12,
    color: "#a0aec0",
    marginBottom: 4,
  },
  menuModalCopyright: {
    fontSize: 11,
    color: "#cbd5e0",
  },
});
